<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Planning\**" />
    <EmbeddedResource Remove="Views\Planning\**" />
    <None Remove="Views\Planning\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fonts\Font Awesome-Brands-Regular-400.otf" />
    <None Remove="Fonts\Font Awesome-Regular-400.otf" />
    <None Remove="Fonts\Font Awesome-Solid-900.otf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\Font Awesome-Brands-Regular-400.otf" />
    <EmbeddedResource Include="Fonts\Font Awesome-Regular-400.otf" />
    <EmbeddedResource Include="Fonts\Font Awesome-Solid-900.otf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="akavache" Version="7.3.1" />
    <PackageReference Include="modernhttpclient" Version="2.4.2" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Shiny" Version="2.3.0.2906" />
    <PackageReference Include="Shiny.Push.FirebaseMessaging" Version="2.3.0.2906" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2662" />
    <PackageReference Include="Xamarin.Essentials.Interfaces" Version="1.8.0" />
    <PackageReference Include="Prism.DryIoc.Forms" Version="8.0.0.1909" />
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="5.0.0.2662" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\AdminPlanningPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AdminUnlinkTruckDriver.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AnomaliesPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AnomalyOperations\CompleteAnomalyPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\AnomalyOperations\TransferAnomalyPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\DriverNotificationPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\LoginPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\MainPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningCreation\AdminAssocDriverSelection.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningCreation\AdminAssocTruckSelection.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningCreation\AdminFreePlanDriverSelection.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningCreation\AdminFreePlanPlanning.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningCreation\AdminFreePlanTruckSelection.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningCreation\PlanningCreationPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningCreation\PlanningTruckDriverSelectionPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\PlanningRevocation\PlanningRevocationPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\VacationCreation\TruckDriverSelectionPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\VacationCreation\VacationCreation.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\VacationReporting.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\VacationReportingFilterDialog.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\WorkingHoursDialog.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\WorkingHoursPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>